### ISSUE TITLE
[Bug] Docker - ConfigNodeClient:255 - The current node may have been down TEndPoint

### ISSUE THREAD

**Issue by MRIIOT** [apache/iotdb#10882]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

[1.1.2-standalone](https://hub.docker.com/layers/apache/iotdb/1.1.2-standalone/images/sha256-a7635f9fddf63b6663825a000d5532e0f6cb2b61672229bcd56817176f4c3516?context=explore)

### Describe the bug and provide the minimal reproduce step

```
  iotdb:
    container_name: iotdb
    image: apache/iotdb:latest
    restart: always
    networks:
      - net1
    #ports:
    #  - "6667:6667/tcp"
    environment:
      - cn_internal_address=iotdb
      - cn_internal_port=10710
      - cn_consensus_port=10720
      - cn_target_config_node_list=iotdb:10710
      - dn_rpc_address=iotdb
      - dn_internal_address=iotdb
      - dn_rpc_port=6667
      - dn_mpp_data_exchange_port=10740
      - dn_schema_region_consensus_port=10750
      - dn_data_region_consensus_port=10760
      - dn_target_config_node_list=iotdb:10710
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/user/volumes/iotdb/data:/iotdb/data
      - /home/user/volumes/iotdb/logs:/iotdb/logs
    labels:
      - traefik.enable=false
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
```

### What did you expect to see?

Successful startup.

### What did you see instead?

ConfigNodeClient:255 - The current node may have been down TEndPoint(ip:iotdb, port:10710),try next node

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
