### ISSUE TITLE
[Bug] iotdb-standalone docker-compose won't start, stuck at "Checking whether the ports are already occupied..."

### ISSUE THREAD

**Issue by hl037** [apache/iotdb#12038]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.


### Version

Archlinux + Docker24.0.7
apache/iotdb:1.3.0-standalone
apache/iotdb:1.2.2-standalone
(I have not tried other versions)

### Describe the bug and provide the minimal reproduce step

docker-compose.yml :
```
version: "3"
services:
  iotdb-service:
    image: apache/iotdb:1.3.0-standalone
    hostname: iotdb-service
    container_name: iotdb-service
    ports:
      - "6667:6667"
    environment:
      - cn_internal_address=iotdb-service
      - cn_internal_port=10710
      - cn_consensus_port=10720
      - cn_seed_config_node=iotdb-service:10710
      - dn_rpc_address=iotdb-service
      - dn_internal_address=iotdb-service
      - dn_rpc_port=6667
      - dn_mpp_data_exchange_port=10740
      - dn_schema_region_consensus_port=10750
      - dn_data_region_consensus_port=10760
      - dn_seed_config_node=iotdb-service:10710
    volumes:
        - ./data:/iotdb/data
        - ./logs:/iotdb/logs
    networks:
      iotdb:
        ipv4_address: 172.18.0.6

networks:
  iotdb:
    external: true
```

commands :
```
docker network create --driver=bridge --subnet=172.18.0.0/16 --gateway=172.18.0.1 iotdb
docker compose up
```

output :
```
[+] Running 1/0
 ✔ Container iotdb-service  Created                                                                                                                                                                                                                                                                                  0.0s 
Attaching to iotdb-service
iotdb-service  | update dn_internal_address /iotdb/conf/iotdb-datanode.properties
iotdb-service  | update dn_data_region_consensus_port /iotdb/conf/iotdb-datanode.properties
iotdb-service  | update cn_internal_port /iotdb/conf/iotdb-confignode.properties
iotdb-service  | update dn_rpc_address /iotdb/conf/iotdb-datanode.properties
iotdb-service  | update dn_mpp_data_exchange_port /iotdb/conf/iotdb-datanode.properties
iotdb-service  | update dn_rpc_port /iotdb/conf/iotdb-datanode.properties
iotdb-service  | update cn_consensus_port /iotdb/conf/iotdb-confignode.properties
iotdb-service  | update cn_seed_config_node /iotdb/conf/iotdb-confignode.properties
iotdb-service  | update cn_internal_address /iotdb/conf/iotdb-confignode.properties
iotdb-service  | update dn_schema_region_consensus_port /iotdb/conf/iotdb-datanode.properties
iotdb-service  | update dn_seed_config_node /iotdb/conf/iotdb-datanode.properties
iotdb-service  | Checking whether the ports are already occupied...
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container iotdb-service  Stopped                                                                                                                                                                                                                                                                                  0.6s 
iotdb-service exited with code 0
canceled
```

### What did you expect to see?

The service to start in less than 5 minutes

### What did you see instead?

The service does not start, is tuck, and the cpu burns at 100% for 10 minutes

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
