### ISSUE TITLE
[Bug] 麒麟系统 docker 部署iotdb，启动后卡在 Checking whether the ports are already occupied...

### ISSUE THREAD

**Issue by FlickerMi** [apache/iotdb#13151]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

iotdb版本：iotdb:1.3.1-standalone
服务器版本：麒麟V10 x86_64
Linux version 4.19.90-52.22.v2207.ky10.x86_64 (KYLINSOFT@COMPILE.MACHINE) (gcc version 7.3.0 (GCC)) #1 SMP Tue Mar 14 12:19:10CST 2023

### Describe the bug and provide the minimal reproduce step

使用docker启动iotdb，**docker-compose.yml**：

```
version : '3.8'

services:
  iotdb:
    container_name: iotdb
    image: apache/iotdb:1.3.1-standalone
    restart: always
    hostname: iotdb-service
    ports:
      - "6667:6667"
      - "31999:31999"
      - "8123:8123"
      - "9003:9003"
    volumes:
      - ./data:/iotdb/data
      - ./logs:/iotdb/logs
      - ./conf:/iotdb/conf
    environment:
      - TZ=Asia/Shanghai
      - enable_rest_service=true
      - cn_internal_address=iotdb-service
      - cn_internal_port=10710
      - cn_consensus_port=10720
      - cn_seed_config_node=iotdb-service:10710
      - dn_rpc_address=iotdb-service
      - dn_internal_address=iotdb-service
      - dn_rpc_port=6667
      - dn_mpp_data_exchange_port=10740
      - dn_schema_region_consensus_port=10750
      - dn_data_region_consensus_port=10760
      - dn_target_config_node_list=iotdb-service:10710
      #- dn_seed_config_node=iotdb-service:10710
    networks:
      - cc-network

networks:
  cc-network:
    external: true
```

docker compose up -d 后，日志卡在Checking whether the ports are already occupied...，并且容器CPU飙升。

![IMG_20240813_174351.jpg](https://github.com/user-attachments/assets/d0c0aabf-9735-4cfe-93ad-9f2c827ee5c3)

**输出日志：**

![IMG_20240813_174333.jpg](https://github.com/user-attachments/assets/78949c7d-1412-4a4d-a033-6c87195e1209)

```
Checking whether the ports are already occupied...
```

### What did you expect to see?

 正常启动

### What did you see instead?

Checking whether the ports are already occupied...

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
试试 dn_target_config_node_list=iotdb-service:10710 恢复成 dn_seed_config_node=iotdb-service:10710 ？

**Comment by FlickerMi** [comment]
> 试试 dn_target_config_node_list=iotdb-service:10710 恢复成 dn_seed_config_node=iotdb-service:10710 ？

还是不行，也是卡在Checking whether the ports are already occupied...

还有其它什么方案能帮助排查问题吗？

**Comment by HTHou** [comment]
少了 dn_internal_port=10730 ？

**Comment by HTHou** [comment]
https://discourse.pi-hole.net/t/pi-hole-docker-lsof-pni-53-using-100-cpu/47484/4 看到一个类似的 lsof 占用cpu 高的情况，试试最后面的这个方法？
<img width="920" alt="image" src="https://github.com/user-attachments/assets/28dab340-f2c2-49e3-9863-4ada071a82ca">

**Comment by FlickerMi** [comment]
@HTHou 已经解决，主要是容器内openfiles的ulimit太高，导致启动iotdb时，lsof命令checkConfigNodePortUsages的时侯挂起了。

解决方法：修改/etc/docker/daemon.json 默认ulimits，设置小点

![image](https://github.com/user-attachments/assets/c3d34b17-6789-4c89-944e-a9e4daa57506)


参考内容：https://unix.stackexchange.com/questions/722948/lsof-is-frozen-inside-the-container

**Comment by Dannyshcn** [comment]
version: '3'
services:
  my_service:
    image: my_image
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

**Comment by wold9168** [comment]
对于使用docker compose的用户，可以考虑将以下设置项加入docker compose相应的服务中：
```yaml
ulimits:
  nofile:
    soft: 65536
    hard: 65536
```
我认为最好在上游的文档中就该问题进行更详细的补充说明，同时考虑将该ulimits设置加入到文档中提供的docker-compose.yml中，并用注释加以说明。让有需要的用户自行删去。
