### ISSUE TITLE
After writeprocessexception, the system rejects INSERT actions .

### ISSUE THREAD

**Issue by kohlersDagger** [apache/iotdb#2217]
**antecedents** --> #2158 

**description**
Thank you for your help in the last issue and the program ran smoothly，occasionally a `WriteProcessException` was thrown, but the data was still written successfully .
But the number of `WriteProcessException` began to increase at about the 103rd hour , then jdbc & cli can't INSERT .
SELECT is not affected . 

**server logs**
![捕获](https://user-images.githubusercontent.com/49938137/101441424-03e04e80-3954-11eb-9481-6134c66d70cc.PNG)

**Comment by HTHou** [comment]
Thank you so much for your feedback! 

Can you please let me know more details to reproduce this.
What is the memory size? 
Did you use the same IoTDB settings and jar like you described in  #2158,  write values to 60000 time series per second?
How did your jar insert data? JDBC or native API?

**Comment by kohlersDagger** [comment]
Yes i use the same IoTDB settings and jar , except `waiting_time_when_insert_blocked` and `max_waiting_time_when_insert_blocked` .
Iotdb server runs in the docker container , the memory size is  8G while running .
The Java program uses the spring boot wIth JDBC framework, and the connection pool configuration is as follows:

```
spring:
  datasource:
    driverClassName: org.apache.iotdb.jdbc.IoTDBDriver
    url: jdbc:iotdb://x:x:x:x:6667/
    username: root
    password: root
    hikari:
      maximum-pool-size: 16
      idle-timeout: 60000
      connection-timeout: 10000
      max-lifetime: 3600000
      pool-name: IoTDB-Pool
```
As for data access layer , the general code logic is as follows :
```
    @Autowired
    private DataSource dataSource;

    public void writeIoTDB(String sql) throws SQLException {
        Connection connection = dataSource.getConnection();
        Statement statement = connection.createStatement();

        statement.executeUpdate(sql);

        statement.close();
        connection.close();
    }
```
what's more ,  `@Async` is used to improve efficiency .
That's all the details.

-------

I plan to reproduce this with a new iotdb of the same version & same jdbc . this may take a while .
